### ISSUE TITLE
undefined 'packageManager' in 'services/unixPackageManager.js'

### ISSUE THREAD

**Issue by Grenadingue** [EIP-SAM/SAM-Solution-Daemon-Client#34]
```
list_installed_packages {} 9
TypeError: Cannot read property 'packageManager' of undefined
    at /home/phong/Dev/SAM-Solution-Daemon-Client/services/unixPackageManager.js:322:26
    at Object.module.exports.list [as list_installed_packages] (/home/phong/Dev/SAM-Solution-Daemon-Client/services/unixPackageManager.js:316:10)
    at Socket.<anonymous> (/home/phong/Dev/SAM-Solution-Daemon-Client/modules/software/exec.js:29:21)
    at Socket.Emitter.emit (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/component-emitter/index.js:131:20)
    at Socket.onevent (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/component-emitter/index.js:131:20)
    at Manager.ondecoded (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/home/phong/Dev/SAM-Solution-Daemon-Client/node_modules/component-bind/index.js:21:15)
```

**Comment by Grenadingue** [comment]
Fixed
Forgotten `npm update node-pacapt` after `npm install`
