### ISSUE TITLE
Software module: Cannot read property 'leave' of undefined

### ISSUE THREAD

**Issue by Grenadingue** [EIP-SAM/SAM-Solution-Daemon-Client#39]
```
TypeError: Cannot read property 'leave' of undefined
    at pacapt.update.then (/home/phong/Dev/SAM-Solution-Daemon-Client/services/unixPackageManager.js:50:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This should be a simple error caused by #36

**Comment by Grenadingue** [comment]
Git usage error, not related with #36 nor reproductible from `#develop`

Fixed
